videos:
  -
    title: La Curación del Sufrimiento
    id: YqfnJE0HkLo
    text: |
      Primera intervención pública de Silo. En un envoltorio más o menos
      poético se explica que el conocimiento más importante para la vida (“la real
      sabiduría”), no coincide con el conocimiento de libros, sino que es una cuestión
      de experiencia personal, íntima. El conocimiento más importante para la vida
      está referido a la comprensión del sufrimiento y su superación. Esta arenga es
      considerada como el acto fundacional del Movimiento Humanista.    
  -
    title: Acto Público en Madrid
    id: dN6wFa_9e7U
    text: |
      Invitado por La Comunidad para el Desarrollo Humano de distintos
      países, Silo emprendió una gira de difusión participando en varios eventos
      públicos. El núcleo de las ideas presentadas por Silo en Madrid se repitió en
      Barcelona, Reykjavik, Frankfurt, Copenhague, Milán, Colombo, París y Ciudad de
      México.
  -
    title: ¿Qué es el Movimiento Humanista?
    id: sfdQKBTKmwk
    text: |
      Extracto de la reunión del Movimiento Humanista realizada en Buenos
      Aires el 4 de enero de 1998. Su fundador, Silo, comenta qué es actualmente el MH.
  -
    title: Historia de la No-violencia
    id: oqEqjHqQF6E
    text: |
      Breve documental acerca de la "Historia de la No-Violencia Activa",
      desde sus comienzos con el Jainismo, Tolstoy, Gandhi, M.L.King y finaliza con SILO,
      su obra, su doctrina y su aplicación en lo social a través del Movimiento Humanista.
  -
    title: El Humanismo
    id: c6K1ZsShOzo
    text: |
      Comentarios de Silo a cerca de "El Humanismo", emitido desde el Centro de Estudios 
      del Parque Punta de Vacas en Abril del 2008.
  -
    title: El Significado de la Paz y la No-violencia en el Momento Actual (extracto)
    id: kNF6TRlYnjw
    text: |
      Exposición de Silo en la 10ª Cumbre de los Nóbel por la Paz. 
      A 40 años después de su primer discurso público, el fundador del Humanismo 
      Universalista e inspirador de la Marcha Mundial por la Paz y la No Violencia, 
      ha convencido de la posibilidad de construir la Nación Humana Universal 
      fundada sobre una cultura de no violencia activa.
    
